name: HomeHub
version: 1.0.0
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  # other existing dependencies

# Add the new dev_dependencies section

dev_dependencies:
  mockito: ^5.0.0
  mocktail: ^0.2.0
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter

